# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Techne < Formula
  desc "AI-powered coding agent with TUI interface"
  homepage "https://github.com/Edcko/techne-code"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Edcko/techne-code/releases/download/v0.1.0/techne_0.1.0_darwin_amd64.tar.gz"
      sha256 "5b0d7603dc8f3aac5f6ed316962cd80cdb87797d92bef2f4c4815a4bf872c6a0"

      define_method(:install) do
        bin.install "techne"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Edcko/techne-code/releases/download/v0.1.0/techne_0.1.0_darwin_arm64.tar.gz"
      sha256 "e41a8404e2da06c69f5e34456a9731774aab073bf9962e21239b1923b8e94edb"

      define_method(:install) do
        bin.install "techne"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Edcko/techne-code/releases/download/v0.1.0/techne_0.1.0_linux_amd64.tar.gz"
      sha256 "6c6c9e3057e131ab87f21749cdb6317e944067776054d19e2f7d2e81fbd1c879"
      define_method(:install) do
        bin.install "techne"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Edcko/techne-code/releases/download/v0.1.0/techne_0.1.0_linux_arm64.tar.gz"
      sha256 "bf8a74a1cb81581ab0adc3f5ba6fac562744febab48eacda83940fd255480c5a"
      define_method(:install) do
        bin.install "techne"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/techne version")
  end
end
